-- Crear tabla CANALES
CREATE TABLE CANALES (
    ID_CN INTEGER NOT NULL,
    NOMBRE_CN VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CN)
);

CREATE UNIQUE INDEX CANALES_PK ON CANALES (ID_CN ASC);

-- Crear tabla TIPOS_CUENTAS
CREATE TABLE TIPOS_CUENTAS (
    ID_TC INTEGER NOT NULL,
    DESCRIPCION_TC VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID_TC)
);

CREATE UNIQUE INDEX TIPOS_CUENTAS_PK ON TIPOS_CUENTAS (ID_TC ASC);

-- Crear tabla PELICULAS
CREATE TABLE PELICULAS (
    ID_PL INT IDENTITY(1,1) PRIMARY KEY,
    TITULO_PL VARCHAR(50) NOT NULL,
    DESCRIPCION_PL VARCHAR(500),
    DURACION_PL VARCHAR(10),
    ELENCO_PL VARCHAR(500),
    URL_PL VARCHAR(100) NOT NULL,
    PORTADA_PL VARCHAR(100) NOT NULL
);

-- Crear tabla SERIES
CREATE TABLE SERIES (
    ID_SR INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_SR VARCHAR(50) NOT NULL,
    DESCRIPCION_SR VARCHAR(500),
    CANT_CAPITULOS_SR INT,
    URL_SR VARCHAR(100) NOT NULL,
    PORTADA_SR VARCHAR(100) NOT NULL
);

-- Crear tabla ESTADOS_CUENTAS
CREATE TABLE ESTADOS_CUENTAS (
    ID_EC INTEGER NOT NULL,
    DESCRIPCION_EC VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_EC)
);

CREATE UNIQUE INDEX ESTADOS_CUENTAS_PK ON ESTADOS_CUENTAS (ID_EC ASC);

-- Crear tabla GENEROS
CREATE TABLE GENEROS (
    ID_GN INTEGER NOT NULL,
    DESCRIPCION_GN VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_GN)
);

CREATE UNIQUE INDEX GENEROS_PK ON GENEROS (ID_GN ASC);

-- Crear tabla USUARIOS
CREATE TABLE USUARIOS (
    ID_USR INT IDENTITY(1,1) PRIMARY KEY,
    ID_TC INTEGER NOT NULL,
    ID_EC INTEGER NOT NULL,
    NOMBRE_USR VARCHAR(50) NOT NULL,
    APELLIDO_USR VARCHAR(50) NOT NULL,
    CORREO_USR VARCHAR(50) NOT NULL,
    PASSWORD_USR VARCHAR(50) NOT NULL,
    FECHA_ALTA_USR DATE NOT NULL,
    FECHA_MODIFICACION_USR DATE NOT NULL,
    VERIFICACION_USR NUMERIC(1) NOT NULL
);

CREATE UNIQUE INDEX USUARIOS_PK ON USUARIOS (ID_USR ASC);
CREATE INDEX RELATION_23_FK ON USUARIOS (ID_TC ASC);
CREATE INDEX RELATION_31_FK ON USUARIOS (ID_EC ASC);

-- Crear tabla CAPITULO_SERIE
CREATE TABLE CAPITULO_SERIE (
    ID_SR INTEGER NOT NULL,
    ID_CP INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_CP VARCHAR(50) NOT NULL,
    DESCRIPCION_CP VARCHAR(100),
    DURACION_CP VARCHAR(10),
    URL_CP VARCHAR(100) NOT NULL,
    PORTADA_CP VARCHAR(100) NOT NULL,
    TEMPORADA_CP VARCHAR(50)
);

-- Añadir la restricción FOREIGN KEY después de crear la tabla SERIES
ALTER TABLE CAPITULO_SERIE
ADD FOREIGN KEY (ID_SR) REFERENCES SERIES (ID_SR);

-- Crear tabla GENEROS_PELICULAS
CREATE TABLE GENEROS_PELICULAS (
    ID_GN INTEGER NOT NULL,
    ID_PL INTEGER NOT NULL,
    PRIMARY KEY (ID_GN, ID_PL)
);

CREATE UNIQUE INDEX RELATION_88_PK ON GENEROS_PELICULAS (ID_GN ASC, ID_PL ASC);
CREATE INDEX RELATION_88_FK2 ON GENEROS_PELICULAS (ID_GN ASC);
CREATE INDEX RELATION_88_FK ON GENEROS_PELICULAS (ID_PL ASC);

-- Crear tabla GENEROS_SERIES
CREATE TABLE GENEROS_SERIES (
    ID_GN INTEGER NOT NULL,
    ID_SR INTEGER NOT NULL,
    PRIMARY KEY (ID_GN, ID_SR)
);

CREATE UNIQUE INDEX RELATION_89_PK ON GENEROS_SERIES (ID_GN ASC, ID_SR ASC);
CREATE INDEX RELATION_89_FK2 ON GENEROS_SERIES (ID_GN ASC);
CREATE INDEX RELATION_89_FK ON GENEROS_SERIES (ID_SR ASC);

-- Crear tabla HISTORIAL_PELICULAS
CREATE TABLE HISTORIAL_PELICULAS (
    ID_PL INTEGER NOT NULL,
    ID_USR INTEGER NOT NULL,
    PRIMARY KEY (ID_PL, ID_USR)
);

CREATE UNIQUE INDEX HISTORIAL_PELICULAS_PK ON HISTORIAL_PELICULAS (ID_PL ASC, ID_USR ASC);
CREATE INDEX HISTORIAL_PELICULAS_FK2 ON HISTORIAL_PELICULAS (ID_PL ASC);
CREATE INDEX HISTORIAL_PELICULAS_FK ON HISTORIAL_PELICULAS (ID_USR ASC);

-- Crear tabla FAVORITOS_PELICULA
CREATE TABLE FAVORITOS_PELICULA (
    ID_PL INTEGER NOT NULL,
    ID_USR INTEGER NOT NULL,
    PRIMARY KEY (ID_PL, ID_USR)
);

CREATE UNIQUE INDEX FAVORITOS_PELICULA_PK ON FAVORITOS_PELICULA (ID_PL ASC, ID_USR ASC);
CREATE INDEX FAVORITOS_PELICULA_FK2 ON FAVORITOS_PELICULA (ID_PL ASC);
CREATE INDEX FAVORITOS_PELICULA_FK ON FAVORITOS_PELICULA (ID_USR ASC);

-- Crear tabla HISTORIAL_SERIES
CREATE TABLE HISTORIAL_SERIES (
    ID_SR INTEGER NOT NULL,
    ID_USR INTEGER NOT NULL,
    PRIMARY KEY (ID_SR, ID_USR)
);

CREATE UNIQUE INDEX HISTORIAL_SERIES_PK ON HISTORIAL_SERIES (ID_SR ASC, ID_USR ASC);
CREATE INDEX HISTORIAL_SERIES_FK2 ON HISTORIAL_SERIES (ID_SR ASC);
CREATE INDEX HISTORIAL_SERIES_FK ON HISTORIAL_SERIES (ID_USR ASC);

-- Crear tabla FAVORITOS_SERIES
CREATE TABLE FAVORITOS_SERIES (
    ID_SR INTEGER NOT NULL,
    ID_USR INTEGER NOT NULL,
    PRIMARY KEY (ID_SR, ID_USR)
);

CREATE UNIQUE INDEX FAVORITOS_SERIES_PK ON FAVORITOS_SERIES (ID_SR ASC, ID_USR ASC);
CREATE INDEX FAVORITOS_SERIES_FK2 ON FAVORITOS_SERIES (ID_SR ASC);
CREATE INDEX FAVORITOS_SERIES_FK ON FAVORITOS_SERIES (ID_USR ASC);