using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Multiplex.Business.DTOs;
using Multiplex.Business.Interfaces;
using Multiplex.Domain.Contexts.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Multiplex.Business.Services
{
    public class TaxonomyService : ITaxonomyService
    {
        private readonly MultiplexContext context;
        private readonly ILogger logger;
        public TaxonomyService(MultiplexContext context, ILogger<UsuariosService> logger)
        {
            this.context = context;
            this.logger = logger;
        }

        public async Task<List<PeliculaDTO>> GetPeliculasPorGenero(int generoId) =>
            await context.GenerosPeliculas.Where(x => x.IdGn == generoId).Select(x => new PeliculaDTO
            {
                Titulo = x.IdPlNavigation.DescripcionPl
            }).ToListAsync();
    }
}
